lib/tpa_web/router.ex
defmodule TpaWeb.Router do
  use TpaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug(Tpa.Auth.Guardian.BasePipeline)
  end

  pipeline :ensure_auth do
    plug(Tpa.Auth.Guardian.Pipeline)
  end

  pipeline :student_auth do
    plug(Tpa.Auth.Guardian.StudentPipeline)
  end

  pipeline :admin_auth do
    plug(Tpa.Auth.Guardian.AdminPipeline)
  end

  scope "/", TpaWeb do
    pipe_through ([:browser, :auth]) # Use the default browser stack

    get("/login", AuthController, :login)
    post("/login", AuthController, :submit_login)
    get("/logout", AuthController, :logout)
    get("/register", StudentController, :new)
    post("/register", StudentController, :create)
  end

  scope "/", TpaWeb do
    pipe_through ([:browser, :ensure_auth])

    get "/", PageController, :index
    resources "/users", UserController
    # resources "/admins", AdminController
    resources "/students", StudentController, except: [:new, :create]
    scope "/student" do
      get "/companies", StudentController, :show_company
      get "/companies/:id/apply", StudentController, :apply_for_company
      get "/companies/:id/withdraw", StudentController, :withdraw_company
      get "/profile", StudentController, :show_profile
    end

    # resources "/companies", CompanyController, only: [:show,:index]
    resources "/companies", CompanyController #, except: [:show,:index]


  end

  scope "/", TpaWeb do
    pipe_through ([:browser, :admin_auth])
    # pipe_through ([:browser])


    resources "/admins", AdminController
    # scope "/admins", TpaWeb do
    # resources "/companies", CompanyController #, except: [:show,:index]
    # end
  end

  # Other scopes may use custom stacks.
  # scope "/api", TpaWeb do
  #   pipe_through :api
  # end
end

lib/tpa_web/views/layout_view.ex
defmodule TpaWeb.LayoutView do
  use TpaWeb, :view
end

lib/tpa_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Tpa!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
              <% claims = Guardian.Plug.current_claims(@conn) %>
              <%= if claims["role"] == "student" do %>
                  <%= link "Profile", to: student_path(@conn,:show_profile), class: "btn btn-line btn-primary"%>
              <% end %>
              <%= if claims["role"] == "admin" do %>
                  <%= link "Home", to: admin_path(@conn,:index), class: "btn btn-line btn-primary"%>
              <% end %>
                  <%= if claims do %>
                   <%= link "Logout", to: auth_path(@conn, :logout), class: "btn btn-line btn-primary" %>                
                  <% end %>
          </ul>
          
        </nav>
        
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>